# This is a required setting, 
# and should be a string that is 
# used as the main title for the 
# project documentation.
# When rendering the theme this 
# setting will be passed as the site_name context variable.
site_name: "Joker's Blog"

# Set the canonical URL of the site. 
# This will add a link tag with the canonical URL to the generated HTML header.
# default: null
site_url:  "http://jokerblog.readthedocs.io/"


# Set the site description. This will add a meta tag to the generated HTML header.
# default: null
site_description: "This is my personal blog as documentr"

# Set the name of the author. This will add a meta tag to the generated HTML header.
# default: null
site_author: "wangzhizhou"

# When set, provides a link to your GitHub or Bitbucket repository on each page.
# default: null
repo_url: "https://github.com/wangzhizhou/JokerBlog"

# When set, provides a link to your GitHub or Bitbucket repository on each page.
# default: 'GitHub' or 'Bitbucket' if the repo_url matches those domains, 
# otherwise null
repo_name: "GitHub"

# When set, provides a link directly to the page in your source repository. 
# This makes it easier to find and edit the source for the page. 
# If repo_url is not set, this option is ignored.
# edit_uri: "edit/master/docs/"
# edit_uri:  blob/master/docs/

# Set the Google analytics tracking configuration.
# default: null
#google_analytics: ["UA-36723568-3", "mkdocs.org"]

# built-in theme
# default: mkdocs
#theme: 
    #name: "readthedocs"
    #custom_dir: "joker_theme"

theme: "readthedocs"
theme_dir: "joker_theme"

# Lets you set the directory containing the documentation source markdown files. 
# This can either be a relative directory, 
# in which case it is resolved relative to the directory 
# containing your configuration file, 
# or it can be an absolute directory path from the root of your local file system.
# default: 'docs'
docs_dir: "docs"


# Lets you set the directory where the output HTML and other files are created. 
# This can either be a relative directory, 
# in which case it is resolved relative to the directory containing your 
# configuration file, or it can be an absolute directory path from the root 
# of your local file system.
# default: 'site'
site_dir: "site"


# Set a list of CSS files in your docs_dir to be included by the theme. 
# For example, the following example will include the extra.css file 
# within the css subdirectory in your docs_dir.
# default: []
# extra_css: []


# Set a list of JavaScript files in your docs_dir to be included by the theme. 
# See the example in extra_css for usage.
# default: []
# http://www.bootcdn.cn/mathjax/readme/ 用来加速js的CDN
extra_javascript:
    - https://cdn.bootcss.com/mathjax/2.7.2/latest.js?config=TeX-AMS-MML_HTMLorMML

# Set a list of templates in your docs_dir to be built by MkDocs. 
# To see more about writing templates for MkDocs read the documentation 
# about custom themes and specifically the section about the variables 
# that are available to templates.
# default: []
# extra_templates: []

# A set of key value pairs, where the values can be any valid YAML construct, 
# that will be passed to the template. 
# This allows for great flexibility when creating custom themes.
# example:
#   extra: 
#       version: 1.0:w
# extra: {} 

# Set the copyright information to be included in the documentation by the theme.
# default: null
copyright: "Created by Wang Zhizhou"


# Set the remote name to push to when using gh-deploy to deploy to Github Pages. 
# This option can be overridden by a command line option in gh-deploy.
remote_name: "origin"


# Set the remote branch to commit to when using gh-deploy to deploy to Github Pages. 
# This option can be overridden by a command line option in gh-deploy.
# default: gh-pages
remote_branch: "gh-pages"


# This setting controls the style used for linking to pages within the documentation.# The default style of use_directory_urls=true creates more user friendly URLs, 
# and is usually what you'll want to use.
use_directory_urls: true


# Determines if a broken link to a page within the documentation is 
# considered a warning or an error (link to a page not listed in the pages setting). 
# Set to true to halt processing when a broken link is found, false prints a warning.
#strict: true


# Determines the address used when running mkdocs serve. 
# Setting this allows you to use another port, 
# or allows you to make the service accessible over your local network 
# by using the 0.0.0.0 address.
# As with all settings, 
# you can set this from the command line, which can be useful, for example:
#   mkdocs serve --dev-addr=0.0.0.0:80
# dev_addr: '127.0.0.1:8000'


# MkDocs uses the Python Markdown library to translate Markdown files into HTML. 
# Python Markdown supports a variety of extensions that customize how pages are 
# formatted. This setting lets you enable a list of extensions beyond the ones that 
# MkDocs uses by default (meta, toc, tables, and fenced_code).
# default: []
# Example:
# markdown_extensions:
#    - smarty
#    - toc:
#        permalink: True
#    - sane_lists
markdown_extensions:
    - mdx_math

# plugins:
#     - search

# This setting is used to determine the set of pages that should be 
# built for the documentation.
# By default pages will contain an alphanumerically sorted, 
# nested list of all the Markdown files found within the docs_dir and 
# its sub-directories. If none are found it will be [] (an empty list).
pages:
    - 'About Me': 'index.md'
    - 'Create your own blog as me': 'How I create this blog.md'
    - 'Z-turn': 
        - 'tech/Network Simulator 2 Installation Guide for Ubuntu.md'
        - 'tech/Learn STL In 30 Minutes.md'
        - 'tech/Installation of Ubuntu 16.04 On UDisk.md'
        - 'tech/Configure Git Server With Ubuntn and Apache 2.md'
        - 'tech/Add Watermark on Video with OpenCV and FFmpeg.md'
        - 'tech/Develop DLNA Using Platinum Library.md'
        - 'tech/FFmpeg and SDL tutorial 1.md'
        - 'tech/FFmpeg compiled on MacOS.md'
        - 'tech/FFmpeg version 3.1.4 example code.md'
        - 'tech/Fmpeg 2.8.6 example code - transcoding.md'
        - 'tech/Nmap Basics.md'
        - 'tech/Use GDB.md'
        - 'tech/User OpenCV to add watermark on a video.md'
        - 'tech/Wireshark Basics.md'
        - 'tech/Optimizing App Startup Time.md'
        - 'tech/OpenVPN on Raspberry Pi.md'
        - 'tech/swift on client and server.md'
        - 'tech/my hardware.md'
        - 'tech/kotlin.md'
        - 'tech/Convert MP4 to GIF With FFmpeg.md'
        - 'tech/jupyterhub.md'
    - 'etc':
        - 'life/alipay-scan-fu-icon.md'
        - 'life/Renting in Beijing.md'
        - 'life/Gu Bei Shui Zhen.md'
    - 'Music':
        - 'music/whistle.md'
    - 'Game':
        - 'minecraft/minecraft.md'
    - 'Me':
        - 'me/My Plan for finding Job.md'
        - 'me/Personal Pre-Work Record.md'
        - 'me/My Financial Planning.md'
        - 'me/Life in Beijing.md'
        - 'me/jokerhub.md'
    - Jenkins:
        - 导览: jenkins/guide/index.md
        - 第一个管道: jenkins/guide/first-pipeline.md
        - 多步管道: jenkins/guide/multiple-steps-pipeline.md
        - 定义执行环境: jenkins/guide/define-execution-environments.md
        - 使用环境变量: jenkins/guide/using-environment-variables.md
        - 记录测试结果: jenkins/guide/recording-test-results-and-artifacts.md
        - 清理和通知: jenkins/guide/cleaning-up-and-notification.md
        - 布署: jenkins/guide/deployment.md
    - ReactiveX:
        - 介绍: reactiveX/introduction.md
        - 可观察的: reactiveX/Observable.md
        - 运算符: reactiveX/Operators.md
        - 单事件可观察对象: reactiveX/Single.md
        - 主题: reactiveX/Subject.md
        - 调度器: reactiveX/Scheduler.md
    - Docker:
        - 简介: docker/start-learn.md
        - 定位: docker/Orientation.md
        - 容器: docker/Container.md
        - 服务: docker/Service.md
        - 机群: docker/Swarm.md
        - 栈: docker/Stack.md
        - 部署应用: docker/Deploy.md
    - Nginx:
        - 新手教程: nginx/beginner-guide.md
        - 主要用途: nginx/application.md
    - iOS:
        - 工作流: "iOS/workflow.md"
        - 持续集成: "iOS/XCode 9 CI.md"
        - Swift4: "iOS/swift4-notes.md"
        - 服务端Swift:
            - 第四章Swfit包管理器: "iOS/swift-on-server/[4]Swift-Package-Manager.md"
            - 第五章使用Kitura写ToDoList: "iOS/swift-on-server/[5]Writng-ToDoList-With-Kitura.md"
        - OC相关: "iOS/objc.md"
        - 逆向工程: "iOS/reverse.md"
        - 应用优化: "iOS/optimization.md"
        - 面试: "iOS/review.md"
        - 十大排序算法: "iOS/sort.md"
    - 乐理基础: 
        - 乐音:
            - "music/theory/tones/Pitches and Clefs.md"
        - 节拍:
            - "music/theory/rhythms/Note Values and Basic Notation.md"
        - 曲调:
            - "music/theory/tunes/Melodies.md"
        - 伴奏:
            - "music/theory/accompanying/Transcribing What You Hear.md"
        - 修饰:
            - "music/theory/embellishing/Harmony and Counterpoint.md"
        - 编曲:
            - "music/theory/arranging/composing and arranging for voices and instruments.md"
        - 附录:
            - "music/theory/appendixes/A.md"