site_name: Joker's Blog

pages:
    - 'Profile': 'index.md'
    - 'Me':
        - 'me/Configure Git Server With Ubuntn and Apache 2.md'
        - 'me/English Personal Resume.md'
        - 'me/Installation of Ubuntu 16.04 On UDisk.md'
        - 'me/Learn STL In 30 Minutes.md'
        - 'me/My plan for finding job.md'
        - 'me/Network Simulator 2 Installation Guide for Ubuntu.md'
        - 'me/Personal Pre-Work Record.md'
    - 'Tech': 
        - 'tech/Add Watermark on Video with OpenCV and FFmpeg.md'
        - 'tech/Develop DLNA Using Platinum Library.md'
        - 'tech/FFmpeg and SDL tutorial 1.md'
        - 'tech/FFmpeg compiled on MacOS.md'
        - 'tech/FFmpeg version 3.1.4 example code.md'
        - 'tech/Fmpeg 2.8.6 example code - transcoding.md'
        - 'tech/Nmap Basics.md'
        - 'tech/Use GDB.md'
        - 'tech/User OpenCV to add watermark on a video.md'
        - 'tech/Wireshark Basics.md'
    - 'life':
        - 'Ali Fu': 'life/alipay-scan-fu-icon.md'

theme: readthedocs
