site_name: Joker's Blog
site_url: null
site_description: 'This is my personal blog as document'
site_author: 'wangzhizhou'

repo_url: 'https://github.com/wangzhizhou/JokerBlog'
repo_name: 'GitHub'
#edit_uri: 'edit/master/docs/'

google_analytics: ['UA-36723568-3', 'mkdocs.org']

theme: readthedocs

strict: true
dev_addr: '0.0.0.0:8000'

copyright: 'created by wangzhizhou'

pages:
    - 'About Me': 'index.md'
    - 'Create your own blog as me': 'How I create this blog.md'
    - 'Z-turn': 
        - 'tech/Network Simulator 2 Installation Guide for Ubuntu.md'
        - 'tech/Learn STL In 30 Minutes.md'
        - 'tech/Installation of Ubuntu 16.04 On UDisk.md'
        - 'tech/Configure Git Server With Ubuntn and Apache 2.md'
        - 'tech/Add Watermark on Video with OpenCV and FFmpeg.md'
        - 'tech/Develop DLNA Using Platinum Library.md'
        - 'tech/FFmpeg and SDL tutorial 1.md'
        - 'tech/FFmpeg compiled on MacOS.md'
        - 'tech/FFmpeg version 3.1.4 example code.md'
        - 'tech/Fmpeg 2.8.6 example code - transcoding.md'
        - 'tech/Nmap Basics.md'
        - 'tech/Use GDB.md'
        - 'tech/User OpenCV to add watermark on a video.md'
        - 'tech/Wireshark Basics.md'
        - 'tech/Optimizing App Startup Time.md'
        - 'tech/OpenVPN on Raspberry Pi.md'
        - 'tech/swift on client and server.md'
        - 'tech/my hardware.md'
        - 'tech/kotlin.md'
    - 'etc':
        - 'life/alipay-scan-fu-icon.md'
        - 'life/Renting in Beijing.md'
    - 'Music':
        - 'music/whistle.md'
    - 'Game':
        - 'minecraft/minecraft.md'
    - 'Me':
        - 'me/English Personal Resume.md'
        - 'me/My Plan for finding Job.md'
        - 'me/Personal Pre-Work Record.md'
        - 'me/My Financial Planning.md'
