site_name: Joker's Blog

pages:
    - 'Profile': 'index.md'
    - 'Me':
        - 'me/English Personal Resume.md'
        - 'me/My Plan for finding Job.md'
        - 'me/Personal Pre-Work Record.md'
        - 'me/My Financial Planning.md'
        - 'me/How I create this blog.md'
    - 'Tech': 
        - 'tech/Network Simulator 2 Installation Guide for Ubuntu.md'
        - 'tech/Learn STL In 30 Minutes.md'
        - 'tech/Installation of Ubuntu 16.04 On UDisk.md'
        - 'tech/Configure Git Server With Ubuntn and Apache 2.md'
        - 'tech/Add Watermark on Video with OpenCV and FFmpeg.md'
        - 'tech/Develop DLNA Using Platinum Library.md'
        - 'tech/FFmpeg and SDL tutorial 1.md'
        - 'tech/FFmpeg compiled on MacOS.md'
        - 'tech/FFmpeg version 3.1.4 example code.md'
        - 'tech/Fmpeg 2.8.6 example code - transcoding.md'
        - 'tech/Nmap Basics.md'
        - 'tech/Use GDB.md'
        - 'tech/User OpenCV to add watermark on a video.md'
        - 'tech/Wireshark Basics.md'
        - 'tech/Optimizing App Startup Time.md'
        - 'tech/OpenVPN on Raspberry Pi.md'
        - 'tech/swift on client and server.md'
        - 'tech/The Key Books On my Computer Road.md'
    - 'life':
        - 'Ali Fu': 'life/alipay-scan-fu-icon.md'
    - 'music':
        - 'music/whistle.md'

theme: readthedocs
